// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BaseNetCore.Domain.Entities;

public partial class LoaiTaiSan
{
    public int Id { get; set; }

    public string MaLoaiTaiSan { get; set; } = null!;

    public string TenLoaiTaiSan { get; set; } = null!;

    public int NhomTaiSanId { get; set; }

    public string? GhiChu { get; set; }

    public int? CachQuanLy { get; set; }

    public string? CachDanhMa { get; set; }
}