// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace BaseNetCore.Domain.Entities;

public partial class NhomTaiSan
{
    public int Id { get; set; }

    public string MaNhom { get; set; } = null!;

    public string TenNhom { get; set; } = null!;

    public int? NhomChaId { get; set; }
}